import alasql from "alasql";

const allData = [
  {
    athlete: 'Michael Phelps',
    age: 23,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 8,
    silver: 0,
    bronze: 0,
    total: 8,
    id: 1,
  },
  {
    athlete: 'Michael Phelps',
    age: 19,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 6,
    silver: 0,
    bronze: 2,
    total: 8,
    id: 2,
  },
  {
    athlete: 'Michael Phelps',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 4,
    silver: 2,
    bronze: 0,
    total: 6,
    id: 3,
  },
  {
    athlete: 'Natalie Coughlin',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 3,
    total: 6,
    id: 4,
  },
  {
    athlete: 'Aleksey Nemov',
    age: 24,
    country: 'Russia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Gymnastics',
    gold: 2,
    silver: 1,
    bronze: 3,
    total: 6,
    id: 5,
  },
  {
    athlete: 'Alicia Coutts',
    age: 24,
    country: 'Australia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
    id: 6,
  },
  {
    athlete: 'Missy Franklin',
    age: 17,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 4,
    silver: 0,
    bronze: 1,
    total: 5,
    id: 7,
  },
  {
    athlete: 'Ryan Lochte',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 5,
    id: 8,
  },
  {
    athlete: 'Allison Schmitt',
    age: 22,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 5,
    id: 9,
  },
  {
    athlete: 'Natalie Coughlin',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 5,
    id: 10,
  },
  {
    athlete: 'Ian Thorpe',
    age: 17,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 2,
    bronze: 0,
    total: 5,
    id: 11,
  },
  {
    athlete: 'Dara Torres',
    age: 33,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 3,
    total: 5,
    id: 12,
  },
  {
    athlete: 'Cindy Klassen',
    age: 26,
    country: 'Canada',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 2,
    total: 5,
    id: 13,
  },
  {
    athlete: 'Nastia Liukin',
    age: 18,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Gymnastics',
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
    id: 14,
  },
  {
    athlete: 'Marit Bjørgen',
    age: 29,
    country: 'Norway',
    year: 2010,
    date: '28/02/2010',
    sport: 'Cross Country Skiing',
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 5,
    id: 15,
  },
  {
    athlete: 'Sun Yang',
    age: 20,
    country: 'China',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 16,
  },
  {
    athlete: 'Kirsty Coventry',
    age: 24,
    country: 'Zimbabwe',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
    id: 17,
  },
  {
    athlete: 'Libby Lenton-Trickett',
    age: 23,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 18,
  },
  {
    athlete: 'Ryan Lochte',
    age: 24,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 4,
    id: 19,
  },
  {
    athlete: 'Inge de Bruijn',
    age: 30,
    country: 'Netherlands',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
    id: 20,
  },
  {
    athlete: 'Petria Thomas',
    age: 28,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: 21,
  },
  {
    athlete: 'Ian Thorpe',
    age: 21,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 22,
  },
  {
    athlete: 'Inge de Bruijn',
    age: 27,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: 23,
  },
  {
    athlete: 'Gary Hall Jr.',
    age: 25,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 24,
  },
  {
    athlete: 'Michael Klim',
    age: 23,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 0,
    total: 4,
    id: 25,
  },
  {
    athlete: "Susie O'Neill",
    age: 27,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
    id: 26,
  },
  {
    athlete: 'Jenny Thompson',
    age: 27,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 4,
    id: 27,
  },
  {
    athlete: 'Pieter van den Hoogenband',
    age: 22,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 4,
    id: 28,
  },
  {
    athlete: 'An Hyeon-Su',
    age: 20,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 4,
    id: 29,
  },
  {
    athlete: 'Aliya Mustafina',
    age: 17,
    country: 'Russia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Gymnastics',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
    id: 30,
  },
  {
    athlete: 'Shawn Johnson',
    age: 16,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Gymnastics',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
    id: 31,
  },
  {
    athlete: 'Dmitry Sautin',
    age: 26,
    country: 'Russia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Diving',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
    id: 32,
  },
  {
    athlete: 'Leontien Zijlaard-van Moorsel',
    age: 30,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Cycling',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: 33,
  },
  {
    athlete: 'Petter Northug Jr.',
    age: 24,
    country: 'Norway',
    year: 2010,
    date: '28/02/2010',
    sport: 'Cross Country Skiing',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 34,
  },
  {
    athlete: 'Ole Einar Bjørndalen',
    age: 28,
    country: 'Norway',
    year: 2002,
    date: '24/02/2002',
    sport: 'Biathlon',
    gold: 4,
    silver: 0,
    bronze: 0,
    total: 4,
    id: 35,
  },
  {
    athlete: 'Janica Kostelic',
    age: 20,
    country: 'Croatia',
    year: 2002,
    date: '24/02/2002',
    sport: 'Alpine Skiing',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: 36,
  },
  {
    athlete: 'Nathan Adrian',
    age: 23,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 37,
  },
  {
    athlete: 'Yannick Agnel',
    age: 20,
    country: 'France',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 38,
  },
  {
    athlete: 'Brittany Elmslie',
    age: 18,
    country: 'Australia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 39,
  },
  {
    athlete: 'Matt Grevers',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 40,
  },
  {
    athlete: 'Ryosuke Irie',
    age: 22,
    country: 'Japan',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 41,
  },
  {
    athlete: 'Cullen Jones',
    age: 28,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 42,
  },
  {
    athlete: 'Ranomi Kromowidjojo',
    age: 21,
    country: 'Netherlands',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 43,
  },
  {
    athlete: 'Camille Muffat',
    age: 22,
    country: 'France',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 44,
  },
  {
    athlete: 'Mel Schlanger',
    age: 25,
    country: 'Australia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 45,
  },
  {
    athlete: 'Emily Seebohm',
    age: 20,
    country: 'Australia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 46,
  },
  {
    athlete: 'Rebecca Soni',
    age: 25,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 47,
  },
  {
    athlete: 'Satomi Suzuki',
    age: 21,
    country: 'Japan',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 48,
  },
  {
    athlete: 'Dana Vollmer',
    age: 24,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 49,
  },
  {
    athlete: 'Alain Bernard',
    age: 25,
    country: 'France',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 50,
  },
  {
    athlete: 'László Cseh Jr.',
    age: 22,
    country: 'Hungary',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 3,
    bronze: 0,
    total: 3,
    id: 51,
  },
  {
    athlete: 'Matt Grevers',
    age: 23,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 52,
  },
  {
    athlete: 'Margaret Hoelzer',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 53,
  },
  {
    athlete: 'Katie Hoff',
    age: 19,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 54,
  },
  {
    athlete: 'Leisel Jones',
    age: 22,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 55,
  },
  {
    athlete: 'Kosuke Kitajima',
    age: 25,
    country: 'Japan',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 56,
  },
  {
    athlete: 'Andrew Lauterstein',
    age: 21,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 57,
  },
  {
    athlete: 'Jason Lezak',
    age: 32,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 58,
  },
  {
    athlete: 'Pang Jiaying',
    age: 23,
    country: 'China',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 59,
  },
  {
    athlete: 'Aaron Peirsol',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 60,
  },
  {
    athlete: 'Steph Rice',
    age: 20,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 61,
  },
  {
    athlete: 'Jess Schipper',
    age: 21,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 3,
    id: 62,
  },
  {
    athlete: 'Rebecca Soni',
    age: 21,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 63,
  },
  {
    athlete: 'Eamon Sullivan',
    age: 22,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 64,
  },
  {
    athlete: 'Dara Torres',
    age: 41,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 3,
    bronze: 0,
    total: 3,
    id: 65,
  },
  {
    athlete: 'Amanda Beard',
    age: 22,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 66,
  },
  {
    athlete: 'Antje Buschschulte',
    age: 25,
    country: 'Germany',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 0,
    silver: 0,
    bronze: 3,
    total: 3,
    id: 67,
  },
  {
    athlete: 'Kirsty Coventry',
    age: 20,
    country: 'Zimbabwe',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 68,
  },
  {
    athlete: 'Ian Crocker',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 69,
  },
  {
    athlete: 'Grant Hackett',
    age: 24,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 70,
  },
  {
    athlete: 'Brendan Hansen',
    age: 22,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 71,
  },
  {
    athlete: 'Jodie Henry',
    age: 20,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 72,
  },
  {
    athlete: 'Otylia Jedrzejczak',
    age: 20,
    country: 'Poland',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 73,
  },
  {
    athlete: 'Leisel Jones',
    age: 18,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 74,
  },
  {
    athlete: 'Kosuke Kitajima',
    age: 21,
    country: 'Japan',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 75,
  },
  {
    athlete: 'Laure Manaudou',
    age: 17,
    country: 'France',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 76,
  },
  {
    athlete: 'Aaron Peirsol',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 77,
  },
  {
    athlete: 'Kaitlin Sandeno',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 78,
  },
  {
    athlete: 'Roland Schoeman',
    age: 24,
    country: 'South Africa',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 79,
  },
  {
    athlete: 'Pieter van den Hoogenband',
    age: 26,
    country: 'Netherlands',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 80,
  },
  {
    athlete: 'Therese Alshammar',
    age: 23,
    country: 'Sweden',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 81,
  },
  {
    athlete: 'Yana Klochkova',
    age: 18,
    country: 'Ukraine',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 82,
  },
  {
    athlete: 'Lenny Krayzelburg',
    age: 24,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 83,
  },
  {
    athlete: 'Massimiliano Rosolino',
    age: 22,
    country: 'Italy',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 84,
  },
  {
    athlete: 'Petria Thomas',
    age: 25,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 85,
  },
  {
    athlete: 'Matt Welsh',
    age: 23,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 86,
  },
  {
    athlete: 'Lee Jeong-Su',
    age: 20,
    country: 'South Korea',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 87,
  },
  {
    athlete: 'Apolo Anton Ohno',
    age: 27,
    country: 'United States',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 88,
  },
  {
    athlete: 'Wang Meng',
    age: 24,
    country: 'China',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 89,
  },
  {
    athlete: 'Jin Seon-Yu',
    age: 17,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 90,
  },
  {
    athlete: 'Lee Ho-Seok',
    age: 19,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 91,
  },
  {
    athlete: 'Apolo Anton Ohno',
    age: 23,
    country: 'United States',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 3,
    id: 92,
  },
  {
    athlete: 'Wang Meng',
    age: 20,
    country: 'China',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 93,
  },
  {
    athlete: 'Marc Gagnon',
    age: 26,
    country: 'Canada',
    year: 2002,
    date: '24/02/2002',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 94,
  },
  {
    athlete: 'Yang Yang (A)',
    age: 25,
    country: 'China',
    year: 2002,
    date: '24/02/2002',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 95,
  },
  {
    athlete: 'Stephanie Beckert',
    age: 21,
    country: 'Germany',
    year: 2010,
    date: '28/02/2010',
    sport: 'Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 96,
  },
  {
    athlete: 'Martina Sáblíková',
    age: 22,
    country: 'Czech Republic',
    year: 2010,
    date: '28/02/2010',
    sport: 'Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 97,
  },
  {
    athlete: 'Enrico Fabris',
    age: 24,
    country: 'Italy',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 98,
  },
  {
    athlete: 'Chad Hedrick',
    age: 28,
    country: 'United States',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 99,
  },
  {
    athlete: 'Jochem Uytdehaage',
    age: 25,
    country: 'Netherlands',
    year: 2002,
    date: '24/02/2002',
    sport: 'Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 100,
  },{
    athlete: 'Michael Phelps',
    age: 23,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 8,
    silver: 0,
    bronze: 0,
    total: 8,
    id: 1,
  },
  {
    athlete: 'Michael Phelps',
    age: 19,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 6,
    silver: 0,
    bronze: 2,
    total: 8,
    id: 2,
  },
  {
    athlete: 'Michael Phelps',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 4,
    silver: 2,
    bronze: 0,
    total: 6,
    id: 3,
  },
  {
    athlete: 'Natalie Coughlin',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 3,
    total: 6,
    id: 4,
  },
  {
    athlete: 'Aleksey Nemov',
    age: 24,
    country: 'Russia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Gymnastics',
    gold: 2,
    silver: 1,
    bronze: 3,
    total: 6,
    id: 5,
  },
  {
    athlete: 'Alicia Coutts',
    age: 24,
    country: 'Australia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
    id: 6,
  },
  {
    athlete: 'Missy Franklin',
    age: 17,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 4,
    silver: 0,
    bronze: 1,
    total: 5,
    id: 7,
  },
  {
    athlete: 'Ryan Lochte',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 5,
    id: 8,
  },
  {
    athlete: 'Allison Schmitt',
    age: 22,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 5,
    id: 9,
  },
  {
    athlete: 'Natalie Coughlin',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 5,
    id: 10,
  },
  {
    athlete: 'Ian Thorpe',
    age: 17,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 2,
    bronze: 0,
    total: 5,
    id: 11,
  },
  {
    athlete: 'Dara Torres',
    age: 33,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 3,
    total: 5,
    id: 12,
  },
  {
    athlete: 'Cindy Klassen',
    age: 26,
    country: 'Canada',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 2,
    total: 5,
    id: 13,
  },
  {
    athlete: 'Nastia Liukin',
    age: 18,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Gymnastics',
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
    id: 14,
  },
  {
    athlete: 'Marit Bjørgen',
    age: 29,
    country: 'Norway',
    year: 2010,
    date: '28/02/2010',
    sport: 'Cross Country Skiing',
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 5,
    id: 15,
  },
  {
    athlete: 'Sun Yang',
    age: 20,
    country: 'China',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 16,
  },
  {
    athlete: 'Kirsty Coventry',
    age: 24,
    country: 'Zimbabwe',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
    id: 17,
  },
  {
    athlete: 'Libby Lenton-Trickett',
    age: 23,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 18,
  },
  {
    athlete: 'Ryan Lochte',
    age: 24,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 4,
    id: 19,
  },
  {
    athlete: 'Inge de Bruijn',
    age: 30,
    country: 'Netherlands',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
    id: 20,
  },
  {
    athlete: 'Petria Thomas',
    age: 28,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: 21,
  },
  {
    athlete: 'Ian Thorpe',
    age: 21,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 22,
  },
  {
    athlete: 'Inge de Bruijn',
    age: 27,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: 23,
  },
  {
    athlete: 'Gary Hall Jr.',
    age: 25,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 24,
  },
  {
    athlete: 'Michael Klim',
    age: 23,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 0,
    total: 4,
    id: 25,
  },
  {
    athlete: "Susie O'Neill",
    age: 27,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
    id: 26,
  },
  {
    athlete: 'Jenny Thompson',
    age: 27,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 4,
    id: 27,
  },
  {
    athlete: 'Pieter van den Hoogenband',
    age: 22,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 4,
    id: 28,
  },
  {
    athlete: 'An Hyeon-Su',
    age: 20,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 4,
    id: 29,
  },
  {
    athlete: 'Aliya Mustafina',
    age: 17,
    country: 'Russia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Gymnastics',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
    id: 30,
  },
  {
    athlete: 'Shawn Johnson',
    age: 16,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Gymnastics',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
    id: 31,
  },
  {
    athlete: 'Dmitry Sautin',
    age: 26,
    country: 'Russia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Diving',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
    id: 32,
  },
  {
    athlete: 'Leontien Zijlaard-van Moorsel',
    age: 30,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Cycling',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: 33,
  },
  {
    athlete: 'Petter Northug Jr.',
    age: 24,
    country: 'Norway',
    year: 2010,
    date: '28/02/2010',
    sport: 'Cross Country Skiing',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: 34,
  },
  {
    athlete: 'Ole Einar Bjørndalen',
    age: 28,
    country: 'Norway',
    year: 2002,
    date: '24/02/2002',
    sport: 'Biathlon',
    gold: 4,
    silver: 0,
    bronze: 0,
    total: 4,
    id: 35,
  },
  {
    athlete: 'Janica Kostelic',
    age: 20,
    country: 'Croatia',
    year: 2002,
    date: '24/02/2002',
    sport: 'Alpine Skiing',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: 36,
  },
  {
    athlete: 'Nathan Adrian',
    age: 23,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 37,
  },
  {
    athlete: 'Yannick Agnel',
    age: 20,
    country: 'France',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 38,
  },
  {
    athlete: 'Brittany Elmslie',
    age: 18,
    country: 'Australia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 39,
  },
  {
    athlete: 'Matt Grevers',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 40,
  },
  {
    athlete: 'Ryosuke Irie',
    age: 22,
    country: 'Japan',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 41,
  },
  {
    athlete: 'Cullen Jones',
    age: 28,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 42,
  },
  {
    athlete: 'Ranomi Kromowidjojo',
    age: 21,
    country: 'Netherlands',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 43,
  },
  {
    athlete: 'Camille Muffat',
    age: 22,
    country: 'France',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 44,
  },
  {
    athlete: 'Mel Schlanger',
    age: 25,
    country: 'Australia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 45,
  },
  {
    athlete: 'Emily Seebohm',
    age: 20,
    country: 'Australia',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 46,
  },
  {
    athlete: 'Rebecca Soni',
    age: 25,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 47,
  },
  {
    athlete: 'Satomi Suzuki',
    age: 21,
    country: 'Japan',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 48,
  },
  {
    athlete: 'Dana Vollmer',
    age: 24,
    country: 'United States',
    year: 2012,
    date: '12/08/2012',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 49,
  },
  {
    athlete: 'Alain Bernard',
    age: 25,
    country: 'France',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 50,
  },
  {
    athlete: 'László Cseh Jr.',
    age: 22,
    country: 'Hungary',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 3,
    bronze: 0,
    total: 3,
    id: 51,
  },
  {
    athlete: 'Matt Grevers',
    age: 23,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 52,
  },
  {
    athlete: 'Margaret Hoelzer',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 53,
  },
  {
    athlete: 'Katie Hoff',
    age: 19,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 54,
  },
  {
    athlete: 'Leisel Jones',
    age: 22,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 55,
  },
  {
    athlete: 'Kosuke Kitajima',
    age: 25,
    country: 'Japan',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 56,
  },
  {
    athlete: 'Andrew Lauterstein',
    age: 21,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 57,
  },
  {
    athlete: 'Jason Lezak',
    age: 32,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 58,
  },
  {
    athlete: 'Pang Jiaying',
    age: 23,
    country: 'China',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 59,
  },
  {
    athlete: 'Aaron Peirsol',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 60,
  },
  {
    athlete: 'Steph Rice',
    age: 20,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 61,
  },
  {
    athlete: 'Jess Schipper',
    age: 21,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 3,
    id: 62,
  },
  {
    athlete: 'Rebecca Soni',
    age: 21,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 63,
  },
  {
    athlete: 'Eamon Sullivan',
    age: 22,
    country: 'Australia',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 64,
  },
  {
    athlete: 'Dara Torres',
    age: 41,
    country: 'United States',
    year: 2008,
    date: '24/08/2008',
    sport: 'Swimming',
    gold: 0,
    silver: 3,
    bronze: 0,
    total: 3,
    id: 65,
  },
  {
    athlete: 'Amanda Beard',
    age: 22,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 66,
  },
  {
    athlete: 'Antje Buschschulte',
    age: 25,
    country: 'Germany',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 0,
    silver: 0,
    bronze: 3,
    total: 3,
    id: 67,
  },
  {
    athlete: 'Kirsty Coventry',
    age: 20,
    country: 'Zimbabwe',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 68,
  },
  {
    athlete: 'Ian Crocker',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 69,
  },
  {
    athlete: 'Grant Hackett',
    age: 24,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 70,
  },
  {
    athlete: 'Brendan Hansen',
    age: 22,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 71,
  },
  {
    athlete: 'Jodie Henry',
    age: 20,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 72,
  },
  {
    athlete: 'Otylia Jedrzejczak',
    age: 20,
    country: 'Poland',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 73,
  },
  {
    athlete: 'Leisel Jones',
    age: 18,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 74,
  },
  {
    athlete: 'Kosuke Kitajima',
    age: 21,
    country: 'Japan',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 75,
  },
  {
    athlete: 'Laure Manaudou',
    age: 17,
    country: 'France',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 76,
  },
  {
    athlete: 'Aaron Peirsol',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 77,
  },
  {
    athlete: 'Kaitlin Sandeno',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 78,
  },
  {
    athlete: 'Roland Schoeman',
    age: 24,
    country: 'South Africa',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 79,
  },
  {
    athlete: 'Pieter van den Hoogenband',
    age: 26,
    country: 'Netherlands',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 80,
  },
  {
    athlete: 'Therese Alshammar',
    age: 23,
    country: 'Sweden',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 81,
  },
  {
    athlete: 'Yana Klochkova',
    age: 18,
    country: 'Ukraine',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 82,
  },
  {
    athlete: 'Lenny Krayzelburg',
    age: 24,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 83,
  },
  {
    athlete: 'Massimiliano Rosolino',
    age: 22,
    country: 'Italy',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 84,
  },
  {
    athlete: 'Petria Thomas',
    age: 25,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 85,
  },
  {
    athlete: 'Matt Welsh',
    age: 23,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 3,
    id: 86,
  },
  {
    athlete: 'Lee Jeong-Su',
    age: 20,
    country: 'South Korea',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 87,
  },
  {
    athlete: 'Apolo Anton Ohno',
    age: 27,
    country: 'United States',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 3,
    id: 88,
  },
  {
    athlete: 'Wang Meng',
    age: 24,
    country: 'China',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 89,
  },
  {
    athlete: 'Jin Seon-Yu',
    age: 17,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 3,
    id: 90,
  },
  {
    athlete: 'Lee Ho-Seok',
    age: 19,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 91,
  },
  {
    athlete: 'Apolo Anton Ohno',
    age: 23,
    country: 'United States',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 3,
    id: 92,
  },
  {
    athlete: 'Wang Meng',
    age: 20,
    country: 'China',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 93,
  },
  {
    athlete: 'Marc Gagnon',
    age: 26,
    country: 'Canada',
    year: 2002,
    date: '24/02/2002',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 94,
  },
  {
    athlete: 'Yang Yang (A)',
    age: 25,
    country: 'China',
    year: 2002,
    date: '24/02/2002',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 95,
  },
  {
    athlete: 'Stephanie Beckert',
    age: 21,
    country: 'Germany',
    year: 2010,
    date: '28/02/2010',
    sport: 'Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 3,
    id: 96,
  },
  {
    athlete: 'Martina Sáblíková',
    age: 22,
    country: 'Czech Republic',
    year: 2010,
    date: '28/02/2010',
    sport: 'Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 97,
  },
  {
    athlete: 'Enrico Fabris',
    age: 24,
    country: 'Italy',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 3,
    id: 98,
  },
  {
    athlete: 'Chad Hedrick',
    age: 28,
    country: 'United States',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 3,
    id: 99,
  },
  {
    athlete: 'Jochem Uytdehaage',
    age: 25,
    country: 'Netherlands',
    year: 2002,
    date: '24/02/2002',
    sport: 'Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 3,
    id: 100,
  },
]


// This fake server uses http://alasql.org/ to mimic how a real server
// might generate sql queries from the Server-Side Row Model request.
// To keep things simple it does the bare minimum to support the example.
export function FakeServer() {
  alasql.options.cache = false;

  return {
    getData: function (request) {
      var results = executeQuery(request);

      return {
        success: true,
        rows: results,
        lastRow: getLastRowIndex(request),
      };
    },
    getCountries: function () {
      var SQL = 'SELECT DISTINCT country FROM ? ORDER BY country ASC';

      return alasql(SQL, [allData]).map(function (x) {
        return x.country;
      });
    },
  };

  function executeQuery(request) {
    var sql = buildSql(request);

    console.log('[FakeServer] - about to execute query:', sql);

    return alasql(sql, [allData]);
  }

  function buildSql(request) {
    return (
      'SELECT * FROM ?' +
      whereSql(request) +
      orderBySql(request) +
      limitSql(request)
    );
  }

  function whereSql(request) {
    var whereParts = [];
    var filterModel = request.filterModel;

    if (filterModel) {
      Object.keys(filterModel).forEach(function (columnKey) {
        var filter = filterModel[columnKey];

        if (filter.filterType === 'set') {
          whereParts.push(
            columnKey + " IN ('" + filter.values.join("', '") + "')"
          );
          return;
        }

        console.log('unsupported filter type: ' + filter.filterType);
      });
    }

    if (whereParts.length > 0) {
      return ' WHERE ' + whereParts.join(' AND ');
    }

    return '';
  }

  function orderBySql(request) {
    var sortModel = request.sortModel;

    if (sortModel.length === 0) return '';

    var sorts = sortModel.map(function (s) {
      return s.colId + ' ' + s.sort.toUpperCase();
    });

    return ' ORDER BY ' + sorts.join(', ');
  }

  function limitSql(request) {
    if (request.endRow == undefined || request.startRow == undefined) {
      return '';
    }
    var blockSize = request.endRow - request.startRow;

    return ' LIMIT ' + blockSize + ' OFFSET ' + request.startRow;
  }

  function getLastRowIndex(request) {
    return executeQuery({ ...request, startRow: undefined, endRow: undefined })
      .length;
  }
}
